In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("F:\crime_project\Crime-Analytics-in-India/crime_dataset_india (1).csv")

In [3]:
df

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
0,1,02-01-2020 0.00,01-01-2020 0.00,01-01-2020 1.11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,Null
1,2,01-01-2020 19.00,01-01-2020 1.00,01-01-2020 6.26,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,Null
2,3,02-01-2020 5.00,01-01-2020 2.00,01-01-2020 14.30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,Null
3,4,01-01-2020 5.00,01-01-2020 3.00,01-01-2020 14.46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 5.00
4,5,01-01-2020 21.00,01-01-2020 4.00,01-01-2020 16.51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,01-08-2024 16.00,07-31-2024 03:00,31-07-2024 5.05,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,Null
40156,40157,31-07-2024 14.00,07-31-2024 04:00,31-07-2024 4.14,Mumbai,300,ILLEGAL POSSESSION,75,F,NaN,Other Crime,2,Yes,29-09-2024 14.00
40157,40158,02-08-2024 3.00,07-31-2024 05:00,31-07-2024 21.33,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,Null
40158,40159,01-08-2024 19.00,07-31-2024 06:00,31-07-2024 11.05,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,Null
40159,40160,31-07-2024 17.00,07-31-2024 07:00,31-07-2024 17.19,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,28-09-2024 17.00

In [4]:
df.describe()

       Report Number    Crime Code   Victim Age  Police Deployed
count   40160.000000  40160.000000  40160.00000     40160.000000
mean    20080.500000    349.360259     44.49126        10.006250
std     11593.337742    144.169205     20.22555         5.467951
min         1.000000    100.000000     10.00000         1.000000
25%     10040.750000    225.000000     27.00000         5.000000
50%     20080.500000    349.000000     44.00000        10.000000
75%     30120.250000    474.000000     62.00000        15.000000
max     40160.000000    599.000000     79.00000        19.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40160 entries, 0 to 40159
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Report Number       40160 non-null  int64
 1   Date Reported       40160 non-null  object
 2   Date of Occurrence  40160 non-null  object
 3   Time of Occurrence  40160 non-null  object
 4   City                40160 non-null  object
 5   Crime Code          40160 non-null  int64
 6   Crime Description   40160 non-null  object
 7   Victim Age          40160 non-null  int64
 8   Victim Gender       40160 non-null  object
 9   Weapon Used         34370 non-null  object
 10  Crime Domain        40160 non-null  object
 11  Police Deployed     40160 non-null  int64
 12  Case Closed         40160 non-null  object
 13  Date Case Closed    40160 non-null  object
dtypes: int64(4), object(10)
memory usage: 4.3+ MB

In [6]:
df.isnull().sum()

Report Number            0
Date Reported            0
Date of Occurrence       0
Time of Occurrence       0
City                     0
Crime Code               0
Crime Description        0
Victim Age               0
Victim Gender            0
Weapon Used           5790
Crime Domain             0
Police Deployed          0
Case Closed              0
Date Case Closed         0
dtype: int64

In [7]:
df.fillna("Unknown", inplace=True)

In [8]:
df.isnull().sum()

Report Number         0
Date Reported         0
Date of Occurrence    0
Time of Occurrence    0
City                  0
Crime Code            0
Crime Description     0
Victim Age            0
Victim Gender         0
Weapon Used           0
Crime Domain          0
Police Deployed       0
Case Closed           0
Date Case Closed      0
dtype: int64

In [9]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [10]:
df.columns

Index(['report_number', 'date_reported', 'date_of_occurrence',
       'time_of_occurrence', 'city', 'crime_code', 'crime_description',
       'victim_age', 'victim_gender', 'weapon_used', 'crime_domain',
       'police_deployed', 'case_closed', 'date_case_closed'],
      dtype='object')

In [11]:
df

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed
0,1,02-01-2020 0.00,01-01-2020 0.00,01-01-2020 1.11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,Null
1,2,01-01-2020 19.00,01-01-2020 1.00,01-01-2020 6.26,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,Null
2,3,02-01-2020 5.00,01-01-2020 2.00,01-01-2020 14.30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,Null
3,4,01-01-2020 5.00,01-01-2020 3.00,01-01-2020 14.46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 5.00
4,5,01-01-2020 21.00,01-01-2020 4.00,01-01-2020 16.51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,01-08-2024 16.00,07-31-2024 03:00,31-07-2024 5.05,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,Null
40156,40157,31-07-2024 14.00,07-31-2024 04:00,31-07-2024 4.14,Mumbai,300,ILLEGAL POSSESSION,75,F,Unknown,Other Crime,2,Yes,29-09-2024 14.00
40157,40158,02-08-2024 3.00,07-31-2024 05:00,31-07-2024 21.33,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,Null
40158,40159,01-08-2024 19.00,07-31-2024 06:00,31-07-2024 11.05,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,Null
40159,40160,31-07-2024 17.00,07-31-2024 07:00,31-07-2024 17.19,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,28-09-2024 17.00

In [12]:
print(df["date_of_occurrence"].head(20).tolist())

['01-01-2020 0.00', '01-01-2020 1.00', '01-01-2020 2.00', '01-01-2020 3.00', '01-01-2020 4.00', '01-01-2020 5.00', '01-01-2020 6.00', '01-01-2020 7.00', '01-01-2020 8.00', '01-01-2020 9.00', '01-01-2020 10.00', '01-01-2020 11.00', '01-01-2020 12.00', '01-01-2020 13.00', '01-01-2020 14.00', '01-01-2020 15.00', '01-01-2020 16.00', '01-01-2020 17.00', '01-01-2020 18.00', '01-01-2020 19.00']

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40160 entries, 0 to 40159
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   report_number       40160 non-null  int64
 1   date_reported       40160 non-null  object
 2   date_of_occurrence  40160 non-null  object
 3   time_of_occurrence  40160 non-null  object
 4   city                40160 non-null  object
 5   crime_code          40160 non-null  int64
 6   crime_description   40160 non-null  object
 7   victim_age          40160 non-null  int64
 8   victim_gender       40160 non-null  object
 9   weapon_used         40160 non-null  object
 10  crime_domain        40160 non-null  object
 11  police_deployed     40160 non-null  int64
 12  case_closed         40160 non-null  object
 13  date_case_closed    40160 non-null  object
dtypes: int64(4), object(10)
memory usage: 4.3+ MB

In [14]:
df["date_of_occurrence"] = df["date_of_occurrence"].str.split().str[0]

In [15]:
df["date_of_occurrence"] = pd.to_datetime(
    df["date_of_occurrence"],
    format="%m-%d-%Y"
)

In [16]:
df

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed
0,1,02-01-2020 0.00,2020-01-01,01-01-2020 1.11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,Null
1,2,01-01-2020 19.00,2020-01-01,01-01-2020 6.26,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,Null
2,3,02-01-2020 5.00,2020-01-01,01-01-2020 14.30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,Null
3,4,01-01-2020 5.00,2020-01-01,01-01-2020 14.46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 5.00
4,5,01-01-2020 21.00,2020-01-01,01-01-2020 16.51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,01-08-2024 16.00,2024-07-31,31-07-2024 5.05,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,Null
40156,40157,31-07-2024 14.00,2024-07-31,31-07-2024 4.14,Mumbai,300,ILLEGAL POSSESSION,75,F,Unknown,Other Crime,2,Yes,29-09-2024 14.00
40157,40158,02-08-2024 3.00,2024-07-31,31-07-2024 21.33,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,Null
40158,40159,01-08-2024 19.00,2024-07-31,31-07-2024 11.05,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,Null
40159,40160,31-07-2024 17.00,2024-07-31,31-07-2024 17.19,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,28-09-2024 17.00

In [17]:
df["date_reported"] = df["date_reported"].str.split().str[0]

In [18]:
df["date_reported"].head(20)

0     02-01-2020
1     01-01-2020
2     02-01-2020
3     01-01-2020
4     01-01-2020
5     02-01-2020
6     01-01-2020
7     02-01-2020
8     04-01-2020
9     03-01-2020
10    02-01-2020
11    03-01-2020
12    01-01-2020
13    02-01-2020
14    02-01-2020
15    02-01-2020
16    03-01-2020
17    04-01-2020
18    02-01-2020
19    03-01-2020
Name: date_reported, dtype: object

In [19]:
print(df["date_reported"].head(20).tolist())

['02-01-2020', '01-01-2020', '02-01-2020', '01-01-2020', '01-01-2020', '02-01-2020', '01-01-2020', '02-01-2020', '04-01-2020', '03-01-2020', '02-01-2020', '03-01-2020', '01-01-2020', '02-01-2020', '02-01-2020', '02-01-2020', '03-01-2020', '04-01-2020', '02-01-2020', '03-01-2020']

In [20]:
df["date_reported"] = pd.to_datetime(
    df["date_reported"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [21]:
df

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed
0,1,2020-01-02,2020-01-01,01-01-2020 1.11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,Null
1,2,2020-01-01,2020-01-01,01-01-2020 6.26,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,Null
2,3,2020-01-02,2020-01-01,01-01-2020 14.30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,Null
3,4,2020-01-01,2020-01-01,01-01-2020 14.46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 5.00
4,5,2020-01-01,2020-01-01,01-01-2020 16.51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,2024-08-01,2024-07-31,31-07-2024 5.05,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,Null
40156,40157,2024-07-31,2024-07-31,31-07-2024 4.14,Mumbai,300,ILLEGAL POSSESSION,75,F,Unknown,Other Crime,2,Yes,29-09-2024 14.00
40157,40158,2024-08-02,2024-07-31,31-07-2024 21.33,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,Null
40158,40159,2024-08-01,2024-07-31,31-07-2024 11.05,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,Null
40159,40160,2024-07-31,2024-07-31,31-07-2024 17.19,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,28-09-2024 17.00

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40160 entries, 0 to 40159
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   report_number       40160 non-null  int64
 1   date_reported       40160 non-null  datetime64[ns]
 2   date_of_occurrence  40160 non-null  datetime64[ns]
 3   time_of_occurrence  40160 non-null  object
 4   city                40160 non-null  object
 5   crime_code          40160 non-null  int64
 6   crime_description   40160 non-null  object
 7   victim_age          40160 non-null  int64
 8   victim_gender       40160 non-null  object
 9   weapon_used         40160 non-null  object
 10  crime_domain        40160 non-null  object
 11  police_deployed     40160 non-null  int64
 12  case_closed         40160 non-null  object
 13  date_case_closed    40160 non-null  object
dtypes: datetime64[ns](2), int64(4), object(8)
memory usage: 4.3+ MB

In [23]:
print(df["time_of_occurrence"].head(10).tolist())

['01-01-2020 1.11', '01-01-2020 6.26', '01-01-2020 14.30', '01-01-2020 14.46', '01-01-2020 16.51', '01-01-2020 17.09', '01-01-2020 14.08', '02-01-2020 6.33', '02-01-2020 6.34', '01-01-2020 17.50']

In [24]:
df["time_of_occurrence"] = df["time_of_occurrence"].str.split().str[1]

print(df["time_of_occurrence"].head())

0     1.11
1     6.26
2    14.30
3    14.46
4    16.51
Name: time_of_occurrence, dtype: object

In [25]:
df["time_of_occurrence"] = df["time_of_occurrence"].str.replace(".", ":", regex=False)

print(df["time_of_occurrence"].head())

0     1:11
1     6:26
2    14:30
3    14:46
4    16:51
Name: time_of_occurrence, dtype: object

In [26]:
df["time_of_occurrence"] = df["time_of_occurrence"].apply(
    lambda x: x if len(x.split(":")[0]) == 2 else "0" + x
)

print(df["time_of_occurrence"].head())

0    01:11
1    06:26
2    14:30
3    14:46
4    16:51
Name: time_of_occurrence, dtype: object

In [27]:
df["time_of_occurrence"] = pd.to_datetime(
    df["time_of_occurrence"],
    format="%H:%M",
    errors="coerce"
).dt.time

In [28]:
df

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed
0,1,2020-01-02,2020-01-01,01:11:00,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,Null
1,2,2020-01-01,2020-01-01,06:26:00,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,Null
2,3,2020-01-02,2020-01-01,14:30:00,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,Null
3,4,2020-01-01,2020-01-01,14:46:00,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 5.00
4,5,2020-01-01,2020-01-01,16:51:00,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,2024-08-01,2024-07-31,05:05:00,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,Null
40156,40157,2024-07-31,2024-07-31,04:14:00,Mumbai,300,ILLEGAL POSSESSION,75,F,Unknown,Other Crime,2,Yes,29-09-2024 14.00
40157,40158,2024-08-02,2024-07-31,21:33:00,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,Null
40158,40159,2024-08-01,2024-07-31,11:05:00,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,Null
40159,40160,2024-07-31,2024-07-31,17:19:00,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,28-09-2024 17.00

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40160 entries, 0 to 40159
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   report_number       40160 non-null  int64
 1   date_reported       40160 non-null  datetime64[ns]
 2   date_of_occurrence  40160 non-null  datetime64[ns]
 3   time_of_occurrence  40160 non-null  object
 4   city                40160 non-null  object
 5   crime_code          40160 non-null  int64
 6   crime_description   40160 non-null  object
 7   victim_age          40160 non-null  int64
 8   victim_gender       40160 non-null  object
 9   weapon_used         40160 non-null  object
 10  crime_domain        40160 non-null  object
 11  police_deployed     40160 non-null  int64
 12  case_closed         40160 non-null  object
 13  date_case_closed    40160 non-null  object
dtypes: datetime64[ns](2), int64(4), object(8)
memory usage: 4.3+ MB

In [30]:
print(df["time_of_occurrence"].head())
print(df["time_of_occurrence"].dtype)

0    01:11:00
1    06:26:00
2    14:30:00
3    14:46:00
4    16:51:00
Name: time_of_occurrence, dtype: object
object

In [31]:
df["crime_hour"] = df["time_of_occurrence"].apply(lambda x: x.hour)

In [32]:
df

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed,crime_hour
0,1,2020-01-02,2020-01-01,01:11:00,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,Null,1
1,2,2020-01-01,2020-01-01,06:26:00,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,Null,6
2,3,2020-01-02,2020-01-01,14:30:00,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,Null,14
3,4,2020-01-01,2020-01-01,14:46:00,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 5.00,14
4,5,2020-01-01,2020-01-01,16:51:00,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21.00,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,2024-08-01,2024-07-31,05:05:00,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,Null,5
40156,40157,2024-07-31,2024-07-31,04:14:00,Mumbai,300,ILLEGAL POSSESSION,75,F,Unknown,Other Crime,2,Yes,29-09-2024 14.00,4
40157,40158,2024-08-02,2024-07-31,21:33:00,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,Null,21
40158,40159,2024-08-01,2024-07-31,11:05:00,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,Null,11
40159,40160,2024-07-31,2024-07-31,17:19:00,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,28-09-2024 17.00,17

In [33]:
df.drop("crime_hour", axis=1, inplace=True)

In [34]:
df

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed
0,1,2020-01-02,2020-01-01,01:11:00,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,Null
1,2,2020-01-01,2020-01-01,06:26:00,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,Null
2,3,2020-01-02,2020-01-01,14:30:00,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,Null
3,4,2020-01-01,2020-01-01,14:46:00,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 5.00
4,5,2020-01-01,2020-01-01,16:51:00,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,2024-08-01,2024-07-31,05:05:00,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,Null
40156,40157,2024-07-31,2024-07-31,04:14:00,Mumbai,300,ILLEGAL POSSESSION,75,F,Unknown,Other Crime,2,Yes,29-09-2024 14.00
40157,40158,2024-08-02,2024-07-31,21:33:00,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,Null
40158,40159,2024-08-01,2024-07-31,11:05:00,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,Null
40159,40160,2024-07-31,2024-07-31,17:19:00,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,28-09-2024 17.00

In [35]:
print(df["date_case_closed"].head(10).tolist())

['Null', 'Null', 'Null', '29-04-2020 5.00', '08-01-2020 21.00', '30-03-2020 3.00', '24-03-2020 16.00', 'Null', 'Null', 'Null']

In [36]:
import pandas as pd

# Replace 'Null' with missing values
df["date_case_closed"] = df["date_case_closed"].replace("Null", pd.NA)

# Extract only the date (works only for non-null values)
df["date_case_closed"] = df["date_case_closed"].str.split().str[0]

# Convert to datetime
df["date_case_closed"] = pd.to_datetime(
    df["date_case_closed"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [37]:
df

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed
0,1,2020-01-02,2020-01-01,01:11:00,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,NaT
1,2,2020-01-01,2020-01-01,06:26:00,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,NaT
2,3,2020-01-02,2020-01-01,14:30:00,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaT
3,4,2020-01-01,2020-01-01,14:46:00,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,2020-04-29
4,5,2020-01-01,2020-01-01,16:51:00,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,2020-01-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,2024-08-01,2024-07-31,05:05:00,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,NaT
40156,40157,2024-07-31,2024-07-31,04:14:00,Mumbai,300,ILLEGAL POSSESSION,75,F,Unknown,Other Crime,2,Yes,2024-09-29
40157,40158,2024-08-02,2024-07-31,21:33:00,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,NaT
40158,40159,2024-08-01,2024-07-31,11:05:00,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,NaT
40159,40160,2024-07-31,2024-07-31,17:19:00,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,2024-09-28

In [38]:
print(df["date_case_closed"].head(10).tolist())

[NaT, NaT, NaT, Timestamp('2020-04-29 00:00:00'), Timestamp('2020-01-08 00:00:00'), Timestamp('2020-03-30 00:00:00'), Timestamp('2020-03-24 00:00:00'), NaT, NaT, NaT]

In [39]:
df["date_case_closed"] = df["date_case_closed"].astype(object)
df["date_case_closed"] = df["date_case_closed"].fillna("Null")

In [40]:
df

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed
0,1,2020-01-02,2020-01-01,01:11:00,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,Null
1,2,2020-01-01,2020-01-01,06:26:00,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,Null
2,3,2020-01-02,2020-01-01,14:30:00,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,Null
3,4,2020-01-01,2020-01-01,14:46:00,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,2020-04-29 00:00:00
4,5,2020-01-01,2020-01-01,16:51:00,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,2020-01-08 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,2024-08-01,2024-07-31,05:05:00,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,Null
40156,40157,2024-07-31,2024-07-31,04:14:00,Mumbai,300,ILLEGAL POSSESSION,75,F,Unknown,Other Crime,2,Yes,2024-09-29 00:00:00
40157,40158,2024-08-02,2024-07-31,21:33:00,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,Null
40158,40159,2024-08-01,2024-07-31,11:05:00,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,Null
40159,40160,2024-07-31,2024-07-31,17:19:00,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,2024-09-28 00:00:00

In [41]:
print(df["date_case_closed"].head(10).tolist())

['Null', 'Null', 'Null', Timestamp('2020-04-29 00:00:00'), Timestamp('2020-01-08 00:00:00'), Timestamp('2020-03-30 00:00:00'), Timestamp('2020-03-24 00:00:00'), 'Null', 'Null', 'Null']

In [42]:
print(df["date_case_closed"].head(10).tolist())

['Null', 'Null', 'Null', Timestamp('2020-04-29 00:00:00'), Timestamp('2020-01-08 00:00:00'), Timestamp('2020-03-30 00:00:00'), Timestamp('2020-03-24 00:00:00'), 'Null', 'Null', 'Null']

In [43]:
df["date_case_closed"] = df["date_case_closed"].apply(
    lambda x: x.strftime("%d-%m-%Y") if isinstance(x, pd.Timestamp) else "Null"
)

In [44]:
df

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed
0,1,2020-01-02,2020-01-01,01:11:00,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,Null
1,2,2020-01-01,2020-01-01,06:26:00,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,Null
2,3,2020-01-02,2020-01-01,14:30:00,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,Null
3,4,2020-01-01,2020-01-01,14:46:00,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020
4,5,2020-01-01,2020-01-01,16:51:00,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,2024-08-01,2024-07-31,05:05:00,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,Null
40156,40157,2024-07-31,2024-07-31,04:14:00,Mumbai,300,ILLEGAL POSSESSION,75,F,Unknown,Other Crime,2,Yes,29-09-2024
40157,40158,2024-08-02,2024-07-31,21:33:00,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,Null
40158,40159,2024-08-01,2024-07-31,11:05:00,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,Null
40159,40160,2024-07-31,2024-07-31,17:19:00,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,28-09-2024

In [45]:
# Create a new column based on time of occurrence
def crime_period(time):
    hour = time.hour

    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

df["crime_occurred"] = df["time_of_occurrence"].apply(crime_period)

In [46]:
df

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed,crime_occurred
0,1,2020-01-02,2020-01-01,01:11:00,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,Null,Night
1,2,2020-01-01,2020-01-01,06:26:00,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,Null,Morning
2,3,2020-01-02,2020-01-01,14:30:00,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,Null,Afternoon
3,4,2020-01-01,2020-01-01,14:46:00,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020,Afternoon
4,5,2020-01-01,2020-01-01,16:51:00,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020,Afternoon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,2024-08-01,2024-07-31,05:05:00,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,Null,Morning
40156,40157,2024-07-31,2024-07-31,04:14:00,Mumbai,300,ILLEGAL POSSESSION,75,F,Unknown,Other Crime,2,Yes,29-09-2024,Night
40157,40158,2024-08-02,2024-07-31,21:33:00,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,Null,Night
40158,40159,2024-08-01,2024-07-31,11:05:00,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,Null,Morning
40159,40160,2024-07-31,2024-07-31,17:19:00,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,28-09-2024,Evening

In [47]:
# Function to categorize age
def age_group(age):
    if age <= 12:
        return "Child"
    elif age <= 19:
        return "Teenager"
    elif age <= 59:
        return "Adult"
    else:
        return "Senior-Citizen"

# Create new column
df["age_group"] = df["victim_age"].apply(age_group)

In [48]:
df

,report_number,date_reported,date_of_occurrence,time_of_occurrence,city,crime_code,crime_description,victim_age,victim_gender,weapon_used,crime_domain,police_deployed,case_closed,date_case_closed,crime_occurred,age_group
0,1,2020-01-02,2020-01-01,01:11:00,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,Null,Night,Teenager
1,2,2020-01-01,2020-01-01,06:26:00,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,Null,Morning,Adult
2,3,2020-01-02,2020-01-01,14:30:00,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,Null,Afternoon,Adult
3,4,2020-01-01,2020-01-01,14:46:00,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020,Afternoon,Adult
4,5,2020-01-01,2020-01-01,16:51:00,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020,Afternoon,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40155,40156,2024-08-01,2024-07-31,05:05:00,Kolkata,312,COUNTERFEITING,78,F,Firearm,Other Crime,12,No,Null,Morning,Senior-Citizen
40156,40157,2024-07-31,2024-07-31,04:14:00,Mumbai,300,ILLEGAL POSSESSION,75,F,Unknown,Other Crime,2,Yes,29-09-2024,Night,Senior-Citizen
40157,40158,2024-08-02,2024-07-31,21:33:00,Kanpur,423,VEHICLE - STOLEN,68,M,Other,Violent Crime,6,No,Null,Night,Senior-Citizen
40158,40159,2024-08-01,2024-07-31,11:05:00,Patna,311,SEXUAL ASSAULT,11,M,Blunt Object,Violent Crime,1,No,Null,Morning,Child
40159,40160,2024-07-31,2024-07-31,17:19:00,Delhi,193,DOMESTIC VIOLENCE,43,F,Poison,Violent Crime,7,Yes,28-09-2024,Evening,Adult

In [49]:
df.isnull().sum()

report_number         0
date_reported         0
date_of_occurrence    0
time_of_occurrence    0
city                  0
crime_code            0
crime_description     0
victim_age            0
victim_gender         0
weapon_used           0
crime_domain          0
police_deployed       0
case_closed           0
date_case_closed      0
crime_occurred        0
age_group             0
dtype: int64

In [57]:
import os

print(os.getcwd())

f:\crime_project\Crime-Analytics-in-India\etl

In [ ]:
df.to_csv("../cleaned_crime_dataset.csv", index=False)